# Generated by Django 2.2.5 on 2019-12-20 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('ids', models.IntegerField()),
                ('activity_name', models.CharField(max_length=250)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('salutation', models.CharField(choices=[('mr', 'mr'), ('mrs', 'mrs'), ('ms', 'ms'), ('miss', 'miss'), ('dr', 'dr')], max_length=4)),
                ('customer_name', models.CharField(max_length=30)),
                ('phone_no', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('remarks', models.TextField()),
                ('outstanding_recievables', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroupModel',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50)),
                ('unit', models.CharField(choices=[('box', 'box'), ('cm', 'cm'), ('dz', 'dz'), ('ft', 'ft'), ('g', 'g'), ('kg', 'kg'), ('km', 'km'), ('lg', 'lg'), ('mg', 'mg'), ('m', 'm'), ('pcs', 'pcs')], max_length=3)),
                ('attribute', models.CharField(max_length=50)),
                ('value', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.TextField(max_length=200)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory_rest_api.ProductGroupModel')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseModel',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory_rest_api.CustomerModel')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory_rest_api.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='SaleModel',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('selling_price', models.FloatField()),
                ('sale_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory_rest_api.CustomerModel')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory_rest_api.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='VendorModel',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=50)),
                ('vendor_email', models.CharField(max_length=50)),
                ('vendor_phno', models.BigIntegerField()),
                ('salutation', models.CharField(choices=[('mr', 'mr'), ('mrs', 'mrs'), ('ms', 'ms'), ('miss', 'miss'), ('dr', 'dr')], max_length=4)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VendorAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('zipcode', models.BigIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('vendor_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory_rest_api.VendorModel')),
            ],
        ),
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('location', models.TextField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory_rest_api.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderModel',
            fields=[
                ('sale_order_no', models.AutoField(primary_key=True, serialize=False)),
                ('customer_notes', models.TextField()),
                ('terms_and_conditions', models.TextField()),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory_rest_api.SaleModel')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderModel',
            fields=[
                ('purchase_order_no', models.AutoField(primary_key=True, serialize=False)),
                ('customer_notes', models.TextField()),
                ('terms_and_conditions', models.TextField()),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory_rest_api.PurchaseModel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Inventory_rest_api.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('invoice_no', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('customer_notes', models.TextField()),
                ('terms_and_conditions', models.TextField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory_rest_api.PurchaseModel')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory_rest_api.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('zipcode', models.BigIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('customer_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory_rest_api.CustomerModel')),
            ],
        ),
    ]
