# Generated by Django 2.2.5 on 2020-01-10 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('activity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ids', models.CharField(max_length=15)),
                ('activity_name', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('description', models.TextField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField()),
                ('address_type', models.CharField(choices=[('customer', 'customer'), ('vendor', 'vendor'), ('organization', 'organization')], default='customer', max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('zipcode', models.BigIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=10, unique=True)),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('bill_time', models.TimeField(auto_now_add=True)),
                ('bill_status', models.CharField(choices=[('draft', 'draft'), ('unpaid', 'unpaid'), ('paid', 'paid')], default='draft', max_length=10)),
                ('vendor_notes', models.TextField()),
                ('terms_and_conditions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('salutation', models.CharField(choices=[('mr', 'mr'), ('mrs', 'mrs'), ('ms', 'ms'), ('miss', 'miss'), ('dr', 'dr')], max_length=4)),
                ('customer_name', models.CharField(max_length=30)),
                ('phone_no', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('remarks', models.TextField()),
                ('outstanding_recievables', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=10, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('invoice_time', models.TimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('invoice_status', models.CharField(choices=[('draft', 'draft'), ('unpaid', 'unpaid'), ('paid', 'paid')], default='draft', max_length=10)),
                ('customer_notes', models.TextField()),
                ('terms_and_conditions', models.TextField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory_rest_api.CustomerModel')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('Phone_number', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('salutation', models.CharField(choices=[('mr', 'mr'), ('mrs', 'mrs'), ('ms', 'ms'), ('miss', 'miss'), ('dr', 'dr')], max_length=4)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('invoice_code', models.CharField(max_length=5)),
                ('salesorder_code', models.CharField(max_length=5)),
                ('purchaseorder_code', models.CharField(max_length=5)),
                ('fiscal_detail', models.CharField(choices=[('1-12', 'jan-dec'), ('2-1', 'feb-jan'), ('3-2', 'mar-feb'), ('4-3', 'apr-mar'), ('5-4', 'may-apr'), ('6-5', 'jun-may'), ('7-6', 'jul-jun'), ('8-7', 'aug-jul'), ('9-8', 'sep-aug'), ('10-9', 'oct-sep'), ('9-10', 'nov-oct'), ('12-11', 'dec-nov')], max_length=8)),
                ('fiscal_end', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroupModel',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50)),
                ('unit', models.CharField(choices=[('box', 'box'), ('cm', 'cm'), ('dz', 'dz'), ('ft', 'ft'), ('g', 'g'), ('kg', 'kg'), ('km', 'km'), ('lg', 'lg'), ('mg', 'mg'), ('m', 'm'), ('pcs', 'pcs')], max_length=3)),
                ('attribute', models.CharField(max_length=50)),
                ('value', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.TextField(max_length=200)),
                ('selling_price', models.FloatField(default=0)),
                ('cost_price', models.FloatField(default=0)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory_rest_api.ProductGroupModel')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_no', models.CharField(max_length=10, unique=True)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('purchase_time', models.TimeField(auto_now_add=True)),
                ('purchase_order_status', models.CharField(choices=[('draft', 'draft'), ('issued', 'issued'), ('confirmed', 'confirmed')], default='draft', max_length=10)),
                ('vendor_notes', models.TextField()),
                ('terms_and_conditions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_order_no', models.CharField(max_length=10, unique=True)),
                ('sales_order_status', models.CharField(choices=[('draft', 'draft'), ('confirmed', 'confirmed'), ('delivered', 'delivered')], default='draft', max_length=10)),
                ('sales_order_date', models.DateField(auto_now_add=True)),
                ('sales_order_time', models.TimeField(auto_now_add=True)),
                ('customer_notes', models.TextField()),
                ('terms_and_conditions', models.TextField()),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Inventory_rest_api.CustomerModel')),
            ],
        ),
        migrations.CreateModel(
            name='VendorModel',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=50)),
                ('vendor_email', models.CharField(max_length=50)),
                ('vendor_phno', models.BigIntegerField()),
                ('salutation', models.CharField(choices=[('mr', 'mr'), ('mrs', 'mrs'), ('ms', 'ms'), ('miss', 'miss'), ('dr', 'dr')], max_length=4)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('product_id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stocks', serialize=False, to='Inventory_rest_api.ProductModel')),
                ('quantity', models.IntegerField()),
                ('location', models.TextField(blank=True, null=True)),
                ('commited', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SalesProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('discount_type', models.CharField(choices=[('', ''), ('rs', 'rs'), ('%', '%')], max_length=3)),
                ('discount_value', models.FloatField()),
                ('adjustment', models.CharField(choices=[('', ''), ('+', '+'), ('-', '-')], max_length=3)),
                ('adjustment_value', models.FloatField()),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory_rest_api.ProductModel')),
                ('sales_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_products', to='Inventory_rest_api.SalesOrderModel')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('discount_type', models.CharField(choices=[('', ''), ('rs', 'rs'), ('%', '%')], max_length=3)),
                ('discount_value', models.FloatField()),
                ('adjustment', models.CharField(choices=[('', ''), ('+', '+'), ('-', '-')], max_length=3)),
                ('adjustment_value', models.FloatField()),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory_rest_api.ProductModel')),
                ('purchase_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_products', to='Inventory_rest_api.PurchaseOrderModel')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='vendor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Inventory_rest_api.VendorModel'),
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Inventory_rest_api.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceProductsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('discount_type', models.CharField(choices=[('', ''), ('rs', 'rs'), ('%', '%')], default='', max_length=3)),
                ('discount_value', models.FloatField(default=0)),
                ('adjustment', models.CharField(choices=[('', ''), ('+', '+'), ('-', '-')], default='', max_length=3)),
                ('adjustment_value', models.FloatField(default=0)),
                ('invoice_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_products', to='Inventory_rest_api.InvoiceModel')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory_rest_api.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='BillProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('discount_type', models.CharField(choices=[('', ''), ('rs', 'rs'), ('%', '%')], max_length=3)),
                ('discount_value', models.FloatField()),
                ('adjustment', models.CharField(choices=[('', ''), ('+', '+'), ('-', '-')], max_length=3)),
                ('adjustment_value', models.FloatField()),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory_rest_api.ProductModel')),
                ('purchase_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_products', to='Inventory_rest_api.BillModel')),
            ],
        ),
        migrations.AddField(
            model_name='billmodel',
            name='vendor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Inventory_rest_api.VendorModel'),
        ),
    ]
