# Generated by Django 2.2.5 on 2020-01-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
