# Generated by Django 2.2.5 on 2020-01-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmodel',
            name='fiscal_end',
            field=models.CharField(default='', max_length=15),
        ),
    ]
