# Generated by Django 2.2.5 on 2019-11-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroupmodel',
            name='value',
            field=models.CharField(default='', max_length=50),
        ),
    ]
