# Generated by Django 2.2.5 on 2019-12-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0002_productgroupmodel_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesModel',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('ids', models.IntegerField()),
                ('activity_name', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
    ]
