# Generated by Django 2.2.5 on 2020-01-11 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0002_auto_20200110_0618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillProductModel',
            new_name='BillProductsModel',
        ),
        migrations.AddField(
            model_name='organizationmodel',
            name='bill_code',
            field=models.CharField(default='Bill-', max_length=5),
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='product_id',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='Inventory_rest_api.ProductModel'),
        ),
    ]
