# Generated by Django 2.2.5 on 2024-01-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0002_auto_20200104_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='invoice_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='organizationmodel',
            name='fiscal_end',
            field=models.CharField(default='', max_length=50),
        ),
    ]
