# Generated by Django 2.2.5 on 2019-12-21 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0002_auto_20191221_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='InvoiceProductsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory_rest_api.InvoiceModel')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory_rest_api.ProductModel')),
            ],
        ),
    ]
