# Generated by Django 2.2.5 on 2020-01-11 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0003_auto_20200111_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory_rest_api.ProductGroupModel'),
        ),
    ]
