# Generated by Django 2.2.5 on 2019-12-22 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0003_auto_20191221_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicemodel',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory_rest_api.CustomerModel'),
        ),
        migrations.AlterField(
            model_name='invoiceproductsmodel',
            name='invoice_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_products', to='Inventory_rest_api.InvoiceModel'),
        ),
        migrations.AlterField(
            model_name='invoiceproductsmodel',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Inventory_rest_api.ProductModel'),
        ),
    ]
