# Generated by Django 2.2.5 on 2020-01-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0003_auto_20240101_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='invoice_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
