# Generated by Django 2.2.5 on 2019-12-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0003_activitiesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiesmodel',
            name='timestamp',
            field=models.CharField(default='', max_length=250),
        ),
    ]
