# Generated by Django 2.2.5 on 2019-12-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0004_auto_20191222_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='invoice_status',
            field=models.CharField(choices=[('draft', 'draft'), ('unpaid', 'unpaid'), ('paid', 'paid')], default='draft', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='activity_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
