# Generated by Django 2.2.5 on 2020-01-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0004_auto_20200111_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmodel',
            name='fiscal_end',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='organizationmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
