# Generated by Django 2.2.5 on 2019-12-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0005_auto_20191222_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordermodel',
            name='purchase_order_status',
            field=models.CharField(choices=[('draft', 'draft'), ('issued', 'issued'), ('confirmed', 'confirmed')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='salesordermodel',
            name='sales_order_status',
            field=models.CharField(choices=[('draft', 'draft'), ('confirmed', 'confirmed'), ('delivered', 'delivered')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='commited',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='invoice_status',
            field=models.CharField(choices=[('draft', 'draft'), ('unpaid', 'unpaid'), ('paid', 'paid')], default='draft', max_length=10),
        ),
    ]
