# Generated by Django 2.2.5 on 2020-01-11 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0005_auto_20200111_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationmodel',
            old_name='id',
            new_name='organization_id',
        ),
    ]
