# Generated by Django 2.2.5 on 2019-12-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0006_auto_20191225_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
