# Generated by Django 2.2.5 on 2020-01-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0006_auto_20200111_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmodel',
            name='organization_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
