# Generated by Django 2.2.5 on 2020-01-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0007_auto_20200111_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmodel',
            name='Phone_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='organizationmodel',
            name='organization_id',
            field=models.IntegerField(blank=True, default=1, primary_key=True, serialize=False),
        ),
    ]
