# Generated by Django 2.2.5 on 2019-12-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0007_auto_20191225_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
