# Generated by Django 2.2.5 on 2020-01-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0008_auto_20200111_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billproductsmodel',
            old_name='purchase_id',
            new_name='bill_id',
        ),
    ]
