# Generated by Django 2.2.5 on 2019-12-25 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0009_auto_20191225_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='product_id',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stocks', serialize=False, to='Inventory_rest_api.ProductModel'),
        ),
    ]
