# Generated by Django 2.2.5 on 2020-01-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0009_auto_20200111_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseProductModel',
            new_name='PurchaseProductsModel',
        ),
    ]
