# Generated by Django 2.2.5 on 2020-01-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0010_auto_20200111_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseproductsmodel',
            old_name='purchase_id',
            new_name='purchase_order_id',
        ),
    ]
