# Generated by Django 2.2.5 on 2020-01-11 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0011_auto_20200111_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProductsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('discount_type', models.CharField(choices=[('', ''), ('rs', 'rs'), ('%', '%')], max_length=3)),
                ('discount_value', models.FloatField()),
                ('adjustment', models.CharField(choices=[('', ''), ('+', '+'), ('-', '-')], max_length=3)),
                ('adjustment_value', models.FloatField()),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory_rest_api.ProductModel')),
            ],
        ),
        migrations.RenameField(
            model_name='salesordermodel',
            old_name='sale_order_no',
            new_name='sales_order_no',
        ),
        migrations.AlterField(
            model_name='purchaseproductsmodel',
            name='purchase_order_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_products', to='Inventory_rest_api.PurchaseOrderModel'),
        ),
        migrations.DeleteModel(
            name='SalesProductModel',
        ),
        migrations.AddField(
            model_name='salesproductsmodel',
            name='sales_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_products', to='Inventory_rest_api.SalesOrderModel'),
        ),
    ]
