# Generated by Django 2.2.5 on 2020-01-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0012_auto_20200111_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='unit',
            field=models.CharField(choices=[('box', 'box'), ('cm', 'cm'), ('dz', 'dz'), ('ft', 'ft'), ('g', 'g'), ('kg', 'kg'), ('km', 'km'), ('lg', 'lg'), ('mg', 'mg'), ('m', 'm'), ('pcs', 'pcs')], default='pcs', max_length=3),
        ),
    ]
