# Generated by Django 3.0.3 on 2020-02-12 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0014_auto_20200211_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='billmodel',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
