# Generated by Django 3.0.3 on 2020-02-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0016_auto_20200217_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billproductsmodel',
            name='adjustment',
        ),
        migrations.RemoveField(
            model_name='billproductsmodel',
            name='adjustment_value',
        ),
        migrations.RemoveField(
            model_name='invoiceproductsmodel',
            name='adjustment',
        ),
        migrations.RemoveField(
            model_name='invoiceproductsmodel',
            name='adjustment_value',
        ),
        migrations.RemoveField(
            model_name='purchaseproductsmodel',
            name='adjustment',
        ),
        migrations.RemoveField(
            model_name='purchaseproductsmodel',
            name='adjustment_value',
        ),
        migrations.RemoveField(
            model_name='salesproductsmodel',
            name='adjustment',
        ),
        migrations.RemoveField(
            model_name='salesproductsmodel',
            name='adjustment_value',
        ),
        migrations.AddField(
            model_name='billmodel',
            name='adjustment',
            field=models.CharField(choices=[('', ''), ('+', '+'), ('-', '-')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='billmodel',
            name='adjustment_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='adjustment',
            field=models.CharField(choices=[('', ''), ('+', '+'), ('-', '-')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='adjustment_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='adjustment',
            field=models.CharField(choices=[('', ''), ('+', '+'), ('-', '-')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='adjustment_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salesordermodel',
            name='adjustment',
            field=models.CharField(choices=[('', ''), ('+', '+'), ('-', '-')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='salesordermodel',
            name='adjustment_value',
            field=models.FloatField(default=0),
        ),
    ]
