# Generated by Django 3.0.3 on 2020-02-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0018_auto_20200223_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='billproductsmodel',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoiceproductsmodel',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseproductsmodel',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salesproductsmodel',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesordermodel',
            name='customer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesordermodel',
            name='terms_and_conditions',
            field=models.TextField(blank=True),
        ),
    ]
