# Generated by Django 3.0.3 on 2020-03-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0019_auto_20200225_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendormodel',
            old_name='vendor_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='vendormodel',
            old_name='vendor_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='vendormodel',
            old_name='vendor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vendormodel',
            old_name='vendor_phno',
            new_name='phone_no',
        ),
    ]
