# Generated by Django 3.0.3 on 2020-03-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_rest_api', '0020_auto_20200304_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicemodel',
            name='due_date',
        ),
    ]
